In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from main import bag_of_words, sentiment_analysis

In [3]:
results_bag, tiempos_bag, df_models_bag, best_model_bag = sentiment_analysis()

all_words doc2vec sentiment_analysis logistic_regression

In [5]:
print(""""entrada\n<class 'pandas.core.frame.DataFrame'> (7848, 1)\n                                                   0\n0  [Born, Christian, HUMILITY, RESPECT, especiall...\n1  [offer, fresh, cut, bank, instrument, lease/sa...\n2  [Wow, five, women, dedicated, given, much, bac...\n3  [happy, assistance, disabled, man, assistance,...\n4  [UN, food, agency, Tuesday, voiced, concern, p...\nToMatrix()\nX_\n<class 'pandas.core.frame.DataFrame'> (7848, 0)\nEmpty DataFrame\nColumns: []\nIndex: [0, 1]\ndf\n<class 'pandas.core.frame.DataFrame'> (7848, 2)\n                                                  x0  \\\n0  [Born, Christian, HUMILITY, RESPECT, especiall...   \n1  [offer, fresh, cut, bank, instrument, lease/sa...   \n\n                                                  x1  \n0  [Born, Christian, HUMILITY, RESPECT, especiall...  \n1  [offer, fresh, cut, bank, instrument, lease/sa...  \nsalida\n<class 'pandas.core.frame.DataFrame'> (7848, 2)\n                                                   0  \\\n0  [Born, Christian, HUMILITY, RESPECT, especiall...   \n1  [offer, fresh, cut, bank, instrument, lease/sa...   \n2  [Wow, five, women, dedicated, given, much, bac...   \n3  [happy, assistance, disabled, man, assistance,...   \n4  [UN, food, agency, Tuesday, voiced, concern, p...   \n\n                                                   1  \n0  [Born, Christian, HUMILITY, RESPECT, especiall...  \n1  [offer, fresh, cut, bank, instrument, lease/sa...  \n2  [Wow, five, women, dedicated, given, much, bac...  \n3  [happy, assistance, disabled, man, assistance,...  \n4  [UN, food, agency, Tuesday, voiced, concern, p...  \nentrada\n<class 'pandas.core.frame.DataFrame'> (7848, 2)\n                                                   0  \\\n0  [Born, Christian, HUMILITY, RESPECT, especiall...   \n1  [offer, fresh, cut, bank, instrument, lease/sa...   \n2  [Wow, five, women, dedicated, given, much, bac...   \n3  [happy, assistance, disabled, man, assistance,...   \n4  [UN, food, agency, Tuesday, voiced, concern, p...   \n\n                                                   1  \n0  [Born, Christian, HUMILITY, RESPECT, especiall...  \n1  [offer, fresh, cut, bank, instrument, lease/sa...  \n2  [Wow, five, women, dedicated, given, much, bac...  \n3  [happy, assistance, disabled, man, assistance,...  \n4  [UN, food, agency, Tuesday, voiced, concern, p...  \nPipeline(steps=[('untokenize', UnTokenize()), ('doc2vec', Doc2Vec())])\nX_\n<class 'pandas.core.frame.DataFrame'> (7848, 1)\n                                                   0\n0  [Born, Christian, HUMILITY, RESPECT, especiall...\n1  [offer, fresh, cut, bank, instrument, lease/sa...\ndf\n<class 'pandas.core.frame.DataFrame'> (7848, 100)\n         0         1         2         3         4         5         6   \\\n0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155   \n1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300   \n\n         7         8         9   ...        90        91        92        93  \\\n0 -0.004796  0.003983 -0.001571  ...  0.001968 -0.001834  0.003429  0.000732   \n1  0.004766 -0.000926 -0.004420  ... -0.003484 -0.000334  0.003600 -0.003707   \n\n         94        95        96        97        98        99  \n0  0.004995  0.002397  0.000063 -0.000416  0.003380  0.001178  \n1 -0.004441  0.004820 -0.004411  0.003721 -0.000087 -0.000200  \n\n[2 rows x 100 columns]\nsalida\n<class 'pandas.core.frame.DataFrame'> (7848, 101)\n                                                 0         1         2    \\\n0  [Born, Christian, HUMILITY, RESPECT, especiall...  0.002344 -0.001731   \n1  [offer, fresh, cut, bank, instrument, lease/sa... -0.004785 -0.004445   \n2  [Wow, five, women, dedicated, given, much, bac...  0.062464  0.004757   \n3  [happy, assistance, disabled, man, assistance,... -0.001770 -0.000452   \n4  [UN, food, agency, Tuesday, voiced, concern, p...  0.001691  0.001937   \n\n        3         4         5         6         7         8         9    ...  \\\n0 -0.002458  0.002918  0.004358  0.000802 -0.003155 -0.004796  0.003983  ...   \n1 -0.000411  0.004265  0.000845  0.001569  0.001300  0.004766 -0.000926  ...   \n2  0.020104  0.029199  0.036762  0.045108 -0.009928 -0.032815 -0.019652  ...   \n3  0.002736  0.002478 -0.003555 -0.002187  0.003552  0.000358 -0.003940  ...   \n4 -0.000167  0.001653 -0.003310 -0.003938  0.001846  0.004500 -0.001118  ...   \n\n        91        92        93        94        95        96        97   \\\n0  0.001968 -0.001834  0.003429  0.000732  0.004995  0.002397  0.000063   \n1 -0.003484 -0.000334  0.003600 -0.003707 -0.004441  0.004820 -0.004411   \n2 -0.002530  0.029477 -0.027981  0.059711 -0.048028 -0.020524  0.014785   \n3 -0.003856  0.002203  0.001426 -0.001703 -0.004051  0.000401  0.004608   \n4 -0.004539 -0.003245 -0.002589 -0.003332  0.004587  0.004807  0.000336   \n\n        98        99        100  \n0 -0.000416  0.003380  0.001178  \n1  0.003721 -0.000087 -0.000200  \n2 -0.037334  0.045465  0.040685  \n3  0.002893 -0.000221  0.000808  \n4 -0.003225 -0.000484  0.003942  \n\n[5 rows x 101 columns]\nentrada\n<class 'pandas.core.frame.DataFrame'> (7848, 101)\n                                                 0         1         2    \\\n0  [Born, Christian, HUMILITY, RESPECT, especiall...  0.002344 -0.001731   \n1  [offer, fresh, cut, bank, instrument, lease/sa... -0.004785 -0.004445   \n2  [Wow, five, women, dedicated, given, much, bac...  0.062464  0.004757   \n3  [happy, assistance, disabled, man, assistance,... -0.001770 -0.000452   \n4  [UN, food, agency, Tuesday, voiced, concern, p...  0.001691  0.001937   \n\n        3         4         5         6         7         8         9    ...  \\\n0 -0.002458  0.002918  0.004358  0.000802 -0.003155 -0.004796  0.003983  ...   \n1 -0.000411  0.004265  0.000845  0.001569  0.001300  0.004766 -0.000926  ...   \n2  0.020104  0.029199  0.036762  0.045108 -0.009928 -0.032815 -0.019652  ...   \n3  0.002736  0.002478 -0.003555 -0.002187  0.003552  0.000358 -0.003940  ...   \n4 -0.000167  0.001653 -0.003310 -0.003938  0.001846  0.004500 -0.001118  ...   \n\n        91        92        93        94        95        96        97   \\\n0  0.001968 -0.001834  0.003429  0.000732  0.004995  0.002397  0.000063   \n1 -0.003484 -0.000334  0.003600 -0.003707 -0.004441  0.004820 -0.004411   \n2 -0.002530  0.029477 -0.027981  0.059711 -0.048028 -0.020524  0.014785   \n3 -0.003856  0.002203  0.001426 -0.001703 -0.004051  0.000401  0.004608   \n4 -0.004539 -0.003245 -0.002589 -0.003332  0.004587  0.004807  0.000336   \n\n        98        99        100  \n0 -0.000416  0.003380  0.001178  \n1  0.003721 -0.000087 -0.000200  \n2 -0.037334  0.045465  0.040685  \n3  0.002893 -0.000221  0.000808  \n4 -0.003225 -0.000484  0.003942  \n\n[5 rows x 101 columns]\nUnTokenize()\nX_\n<class 'pandas.core.frame.DataFrame'> (7848, 100)\n        1         2         3         4         5         6         7    \\\n0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155   \n1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300   \n\n        8         9         10   ...       91        92        93        94   \\\n0 -0.004796  0.003983 -0.001571  ...  0.001968 -0.001834  0.003429  0.000732   \n1  0.004766 -0.000926 -0.004420  ... -0.003484 -0.000334  0.003600 -0.003707   \n\n        95        96        97        98        99        100  \n0  0.004995  0.002397  0.000063 -0.000416  0.003380  0.001178  \n1 -0.004441  0.004820 -0.004411  0.003721 -0.000087 -0.000200  \n\n[2 rows x 100 columns]\ndf\n<class 'pandas.core.frame.DataFrame'> (7848, 1)\n                                                   0\n0  Born Christian HUMILITY RESPECT especially eld...\n1  offer fresh cut bank instrument lease/sale BG ...\nsalida\n<class 'pandas.core.frame.DataFrame'> (7848, 101)\n        0         1         2         3         4         5         6    \\\n0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155   \n1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300   \n2  0.062464  0.004757  0.020104  0.029199  0.036762  0.045108 -0.009928   \n3 -0.001770 -0.000452  0.002736  0.002478 -0.003555 -0.002187  0.003552   \n4  0.001691  0.001937 -0.000167  0.001653 -0.003310 -0.003938  0.001846   \n\n        7         8         9    ...       91        92        93        94   \\\n0 -0.004796  0.003983 -0.001571  ... -0.001834  0.003429  0.000732  0.004995   \n1  0.004766 -0.000926 -0.004420  ... -0.000334  0.003600 -0.003707 -0.004441   \n2 -0.032815 -0.019652  0.000585  ...  0.029477 -0.027981  0.059711 -0.048028   \n3  0.000358 -0.003940  0.004185  ...  0.002203  0.001426 -0.001703 -0.004051   \n4  0.004500 -0.001118 -0.002016  ... -0.003245 -0.002589 -0.003332  0.004587   \n\n        95        96        97        98        99   \\\n0  0.002397  0.000063 -0.000416  0.003380  0.001178   \n1  0.004820 -0.004411  0.003721 -0.000087 -0.000200   \n2 -0.020524  0.014785 -0.037334  0.045465  0.040685   \n3  0.000401  0.004608  0.002893 -0.000221  0.000808   \n4  0.004807  0.000336 -0.003225 -0.000484  0.003942   \n\n                                                 100  \n0  Born Christian HUMILITY RESPECT especially eld...  \n1  offer fresh cut bank instrument lease/sale BG ...  \n2  Wow five women dedicated given much back need ...  \n3  happy assistance disabled man assistance getti...  \n4  UN food agency Tuesday voiced concern plight r...  \n\n[5 rows x 101 columns]\nentrada\n<class 'pandas.core.frame.DataFrame'> (7848, 101)\n        0         1         2         3         4         5         6    \\\n0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155   \n1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300   \n2  0.062464  0.004757  0.020104  0.029199  0.036762  0.045108 -0.009928   \n3 -0.001770 -0.000452  0.002736  0.002478 -0.003555 -0.002187  0.003552   \n4  0.001691  0.001937 -0.000167  0.001653 -0.003310 -0.003938  0.001846   \n\n        7         8         9    ...       91        92        93        94   \\\n0 -0.004796  0.003983 -0.001571  ... -0.001834  0.003429  0.000732  0.004995   \n1  0.004766 -0.000926 -0.004420  ... -0.000334  0.003600 -0.003707 -0.004441   \n2 -0.032815 -0.019652  0.000585  ...  0.029477 -0.027981  0.059711 -0.048028   \n3  0.000358 -0.003940  0.004185  ...  0.002203  0.001426 -0.001703 -0.004051   \n4  0.004500 -0.001118 -0.002016  ... -0.003245 -0.002589 -0.003332  0.004587   \n\n        95        96        97        98        99   \\\n0  0.002397  0.000063 -0.000416  0.003380  0.001178   \n1  0.004820 -0.004411  0.003721 -0.000087 -0.000200   \n2 -0.020524  0.014785 -0.037334  0.045465  0.040685   \n3  0.000401  0.004608  0.002893 -0.000221  0.000808   \n4  0.004807  0.000336 -0.003225 -0.000484  0.003942   \n\n                                                 100  \n0  Born Christian HUMILITY RESPECT especially eld...  \n1  offer fresh cut bank instrument lease/sale BG ...  \n2  Wow five women dedicated given much back need ...  \n3  happy assistance disabled man assistance getti...  \n4  UN food agency Tuesday voiced concern plight r...  \n\n[5 rows x 101 columns]\nAnalisisSentimiento()\n""")

"entrada
<class 'pandas.core.frame.DataFrame'> (7848, 1)
                                                   0
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...
2  [Wow, five, women, dedicated, given, much, bac...
3  [happy, assistance, disabled, man, assistance,...
4  [UN, food, agency, Tuesday, voiced, concern, p...
ToMatrix()
X_
<class 'pandas.core.frame.DataFrame'> (7848, 0)
Empty DataFrame
Columns: []
Index: [0, 1]
df
<class 'pandas.core.frame.DataFrame'> (7848, 2)
                                                  x0  \
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...

                                                  x1
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...
salida
<class 'pandas.core.frame.DataFrame'> (7848, 2)
                                                   0  \
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...
2  [Wow, five, women, dedicated, given, much, bac...
3  [happy, assistance, disabled, man, assistance,...
4  [UN, food, agency, Tuesday, voiced, concern, p...

                                                   1
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...
2  [Wow, five, women, dedicated, given, much, bac...
3  [happy, assistance, disabled, man, assistance,...
4  [UN, food, agency, Tuesday, voiced, concern, p...
entrada
<class 'pandas.core.frame.DataFrame'> (7848, 2)
                                                   0  \
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...
2  [Wow, five, women, dedicated, given, much, bac...
3  [happy, assistance, disabled, man, assistance,...
4  [UN, food, agency, Tuesday, voiced, concern, p...

                                                   1
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...
2  [Wow, five, women, dedicated, given, much, bac...
3  [happy, assistance, disabled, man, assistance,...
4  [UN, food, agency, Tuesday, voiced, concern, p...
Pipeline(steps=[('untokenize', UnTokenize()), ('doc2vec', Doc2Vec())])
X_
<class 'pandas.core.frame.DataFrame'> (7848, 1)
                                                   0
0  [Born, Christian, HUMILITY, RESPECT, especiall...
1  [offer, fresh, cut, bank, instrument, lease/sa...
df
<class 'pandas.core.frame.DataFrame'> (7848, 100)
         0         1         2         3         4         5         6   \
0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155
1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300

         7         8         9   ...        90        91        92        93  \
0 -0.004796  0.003983 -0.001571  ...  0.001968 -0.001834  0.003429  0.000732
1  0.004766 -0.000926 -0.004420  ... -0.003484 -0.000334  0.003600 -0.003707

         94        95        96        97        98        99
0  0.004995  0.002397  0.000063 -0.000416  0.003380  0.001178
1 -0.004441  0.004820 -0.004411  0.003721 -0.000087 -0.000200

[2 rows x 100 columns]
salida
<class 'pandas.core.frame.DataFrame'> (7848, 101)
                                                 0         1         2    \
0  [Born, Christian, HUMILITY, RESPECT, especiall...  0.002344 -0.001731
1  [offer, fresh, cut, bank, instrument, lease/sa... -0.004785 -0.004445
2  [Wow, five, women, dedicated, given, much, bac...  0.062464  0.004757
3  [happy, assistance, disabled, man, assistance,... -0.001770 -0.000452
4  [UN, food, agency, Tuesday, voiced, concern, p...  0.001691  0.001937

        3         4         5         6         7         8         9    ...  \
0 -0.002458  0.002918  0.004358  0.000802 -0.003155 -0.004796  0.003983  ...
1 -0.000411  0.004265  0.000845  0.001569  0.001300  0.004766 -0.000926  ...
2  0.020104  0.029199  0.036762  0.045108 -0.009928 -0.032815 -0.019652  ...
3  0.002736  0.002478 -0.003555 -0.002187  0.003552  0.000358 -0.003940  ...
4 -0.000167  0.001653 -0.003310 -0.003938  0.001846  0.004500 -0.001118  ...

        91        92        93        94        95        96        97   \
0  0.001968 -0.001834  0.003429  0.000732  0.004995  0.002397  0.000063
1 -0.003484 -0.000334  0.003600 -0.003707 -0.004441  0.004820 -0.004411
2 -0.002530  0.029477 -0.027981  0.059711 -0.048028 -0.020524  0.014785
3 -0.003856  0.002203  0.001426 -0.001703 -0.004051  0.000401  0.004608
4 -0.004539 -0.003245 -0.002589 -0.003332  0.004587  0.004807  0.000336

        98        99        100
0 -0.000416  0.003380  0.001178
1  0.003721 -0.000087 -0.000200
2 -0.037334  0.045465  0.040685
3  0.002893 -0.000221  0.000808
4 -0.003225 -0.000484  0.003942

[5 rows x 101 columns]
entrada
<class 'pandas.core.frame.DataFrame'> (7848, 101)
                                                 0         1         2    \
0  [Born, Christian, HUMILITY, RESPECT, especiall...  0.002344 -0.001731
1  [offer, fresh, cut, bank, instrument, lease/sa... -0.004785 -0.004445
2  [Wow, five, women, dedicated, given, much, bac...  0.062464  0.004757
3  [happy, assistance, disabled, man, assistance,... -0.001770 -0.000452
4  [UN, food, agency, Tuesday, voiced, concern, p...  0.001691  0.001937

        3         4         5         6         7         8         9    ...  \
0 -0.002458  0.002918  0.004358  0.000802 -0.003155 -0.004796  0.003983  ...
1 -0.000411  0.004265  0.000845  0.001569  0.001300  0.004766 -0.000926  ...
2  0.020104  0.029199  0.036762  0.045108 -0.009928 -0.032815 -0.019652  ...
3  0.002736  0.002478 -0.003555 -0.002187  0.003552  0.000358 -0.003940  ...
4 -0.000167  0.001653 -0.003310 -0.003938  0.001846  0.004500 -0.001118  ...

        91        92        93        94        95        96        97   \
0  0.001968 -0.001834  0.003429  0.000732  0.004995  0.002397  0.000063
1 -0.003484 -0.000334  0.003600 -0.003707 -0.004441  0.004820 -0.004411
2 -0.002530  0.029477 -0.027981  0.059711 -0.048028 -0.020524  0.014785
3 -0.003856  0.002203  0.001426 -0.001703 -0.004051  0.000401  0.004608
4 -0.004539 -0.003245 -0.002589 -0.003332  0.004587  0.004807  0.000336

        98        99        100
0 -0.000416  0.003380  0.001178
1  0.003721 -0.000087 -0.000200
2 -0.037334  0.045465  0.040685
3  0.002893 -0.000221  0.000808
4 -0.003225 -0.000484  0.003942

[5 rows x 101 columns]
UnTokenize()
X_
<class 'pandas.core.frame.DataFrame'> (7848, 100)
        1         2         3         4         5         6         7    \
0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155
1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300

        8         9         10   ...       91        92        93        94   \
0 -0.004796  0.003983 -0.001571  ...  0.001968 -0.001834  0.003429  0.000732
1  0.004766 -0.000926 -0.004420  ... -0.003484 -0.000334  0.003600 -0.003707

        95        96        97        98        99        100
0  0.004995  0.002397  0.000063 -0.000416  0.003380  0.001178
1 -0.004441  0.004820 -0.004411  0.003721 -0.000087 -0.000200

[2 rows x 100 columns]
df
<class 'pandas.core.frame.DataFrame'> (7848, 1)
                                                   0
0  Born Christian HUMILITY RESPECT especially eld...
1  offer fresh cut bank instrument lease/sale BG ...
salida
<class 'pandas.core.frame.DataFrame'> (7848, 101)
        0         1         2         3         4         5         6    \
0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155
1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300
2  0.062464  0.004757  0.020104  0.029199  0.036762  0.045108 -0.009928
3 -0.001770 -0.000452  0.002736  0.002478 -0.003555 -0.002187  0.003552
4  0.001691  0.001937 -0.000167  0.001653 -0.003310 -0.003938  0.001846

        7         8         9    ...       91        92        93        94   \
0 -0.004796  0.003983 -0.001571  ... -0.001834  0.003429  0.000732  0.004995
1  0.004766 -0.000926 -0.004420  ... -0.000334  0.003600 -0.003707 -0.004441
2 -0.032815 -0.019652  0.000585  ...  0.029477 -0.027981  0.059711 -0.048028
3  0.000358 -0.003940  0.004185  ...  0.002203  0.001426 -0.001703 -0.004051
4  0.004500 -0.001118 -0.002016  ... -0.003245 -0.002589 -0.003332  0.004587

        95        96        97        98        99   \
0  0.002397  0.000063 -0.000416  0.003380  0.001178
1  0.004820 -0.004411  0.003721 -0.000087 -0.000200
2 -0.020524  0.014785 -0.037334  0.045465  0.040685
3  0.000401  0.004608  0.002893 -0.000221  0.000808
4  0.004807  0.000336 -0.003225 -0.000484  0.003942

                                                 100
0  Born Christian HUMILITY RESPECT especially eld...
1  offer fresh cut bank instrument lease/sale BG ...
2  Wow five women dedicated given much back need ...
3  happy assistance disabled man assistance getti...
4  UN food agency Tuesday voiced concern plight r...

[5 rows x 101 columns]
entrada
<class 'pandas.core.frame.DataFrame'> (7848, 101)
        0         1         2         3         4         5         6    \
0  0.002344 -0.001731 -0.002458  0.002918  0.004358  0.000802 -0.003155
1 -0.004785 -0.004445 -0.000411  0.004265  0.000845  0.001569  0.001300
2  0.062464  0.004757  0.020104  0.029199  0.036762  0.045108 -0.009928
3 -0.001770 -0.000452  0.002736  0.002478 -0.003555 -0.002187  0.003552
4  0.001691  0.001937 -0.000167  0.001653 -0.003310 -0.003938  0.001846

        7         8         9    ...       91        92        93        94   \
0 -0.004796  0.003983 -0.001571  ... -0.001834  0.003429  0.000732  0.004995
1  0.004766 -0.000926 -0.004420  ... -0.000334  0.003600 -0.003707 -0.004441
2 -0.032815 -0.019652  0.000585  ...  0.029477 -0.027981  0.059711 -0.048028
3  0.000358 -0.003940  0.004185  ...  0.002203  0.001426 -0.001703 -0.004051
4  0.004500 -0.001118 -0.002016  ... -0.003245 -0.002589 -0.003332  0.004587

        95        96        97        98        99   \
0  0.002397  0.000063 -0.000416  0.003380  0.001178
1  0.004820 -0.004411  0.003721 -0.000087 -0.000200
2 -0.020524  0.014785 -0.037334  0.045465  0.040685
3  0.000401  0.004608  0.002893 -0.000221  0.000808
4  0.004807  0.000336 -0.003225 -0.000484  0.003942

                                                 100
0  Born Christian HUMILITY RESPECT especially eld...
1  offer fresh cut bank instrument lease/sale BG ...
2  Wow five women dedicated given much back need ...
3  happy assistance disabled man assistance getti...
4  UN food agency Tuesday voiced concern plight r...

[5 rows x 101 columns]
AnalisisSentimiento()